### ISSUE TITLE
App not running in development

### ISSUE THREAD

**Issue by kian1213** [kenken023/Wish-HarmonyOS#9]
Always getting this error when I run `npx react-native run-android`:

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1212 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
185 actionable tasks: 2 executed, 183 up-to-date
/home/christian/workspace/cit/harmony/Wish-HarmonyOS/Wish1075/android/app/src/main/java/com/wishfm/mobileapp/MainActivity.java:17: error: incompatible types: int cannot be converted to boolean
        SplashScreen.show(this, R.style.SplashScreenTheme);
                                       ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/home/christian/workspace/cit/harmony/Wish-HarmonyOS/Wish1075/android/app/src/main/java/com/wishfm/mobileapp/MainActivity.java:17: error: incompatible types: int cannot be converted to boolean
        SplashScreen.show(this, R.style.SplashScreenTheme);
                                       ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (/home/christian/workspace/cit/harmony/Wish-HarmonyOS/Wish1075/node_modules/execa/index.js:174:9)
    at /home/christian/workspace/cit/harmony/Wish-HarmonyOS/Wish1075/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/home/christian/workspace/cit/harmony/Wish-HarmonyOS/Wish1075/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/christian/workspace/cit/harmony/Wish-HarmonyOS/Wish1075/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
christian@dev:~/workspace/cit/harmony/Wish-HarmonyOS/Wish1075$ 

```

I tried doing these:

- cloned the latest develop branch into seperate folder
- removed `node_modules` directory then re run `npm install`
- removed `/.gradle` so I can generate new one.

I still get same error.

**Comment by kian1213** [comment]
Already fixed after pulling latest commit.
